on: pull_request

# Sets permissions of the GITHUB_TOKEN to allow write pull-requests
permissions:
  pull-requests: write

jobs:
  delta-typescript-graph-job:
    runs-on: ubuntu-latest
    name: Delta TypeScript Graph
    steps:
      - name: Checkout
        uses: actions/checkout@2d7d9f7ff5b310f983d059b68785b3c74d8b8edd # specify latest version
      - uses: ysk8hori/delta-typescript-graph-action@v1.0.3 # specify latest version
